---
revision: 0
name: meta
version: 0.2.0
title: Meta
summary: Ruby Project Metadata Specification
description:
  Metaspecs are the bomb! 
requirements:
  - name: qed
    groups:
      - test
  - name: ae
    groups:
      - test
authors:
  - name: trans
    email: transfire@gmail.com
  - name: postmodern
    website: 'http://trans.github.com'
copyrights: 
  - year: 2011
    holder: Trans
    license: BSD-2-Clause
  - year: 2011
    holder: Postmodern
    license: BSD-2-Clause
resources:
  home: http://rubyworks.github.com/meta
  code: http://github.com/rubyworks/meta
  mail: http://google.groups.com/groups/rubyworks-mailinglist
