---
revision: 0
source: meta.yml
name: meta
version: 0.2.0
title: Meta
summary: Definitive Ruby Project Metadata
description:
  The .meta specifications are the bomb! 
requirements:
  - name: qed
    groups:
      - test
  - name: ae
    groups:
      - test
authors:
  - name: trans
    email: transfire@gmail.com
  - name: postmodern
    website: 'http://trans.github.com'
copyrights: 
  - year: 2011
    holder: Trans
    license: BSD-2-Clause
  - year: 2011
    holder: Postmodern
    license: BSD-2-Clause
resources:
  homepage: http://rubyworks.github.com/meta
  source: http://github.com/rubyworks/meta

