#!/usr/bin/env ruby
 
name    'rumbler'
version '0.1.0'

title   'Rumbler'
summary 'Ruby Metadata Enabler'

description "Rumbler gives Ruby project's a unified format for " \
            "reusable project metadata."

authors 'trans <transfire@gmail.com>',
        'postmodern (http://trans.github.com)'

requirements 'qed (test)',
             'ae  (test)'

repositories(
  'upstream' => 'http://github.com/rubyworks/rumbler/rumbler.git'
)

resources(
  'home' => 'http://rubyworks.github.com/rumbler',
  'code' => 'http://github.com/rubyworks/rumbler'
)

categories 'metadata'

copyrights(
  '2011 Ruby Works (BSD-2-Clause)',
  '2011 Postmodern (BSD-2-Clause)'
)

